'use client';

import { createClient } from '@/lib/supabase/client';
import { User } from '@supabase/supabase-js';
import { Check, Plus } from 'lucide-react';
import Link from 'next/link';
import React, { useCallback, useEffect, useState } from 'react';

import { useGlobalAudio } from '@/lib/contexts/AudioContext';
import { logWarning } from '@/lib/utils/logger';
import { Button } from './ui/button';
import GlitchWordmark from './ui/glitch-wordmark';
import { Icons } from './ui/icons';

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0W13RkH
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
export const Hero = React.memo(() => {
  const [user, setUser] = useState<User | null>(null);
  const { playOverlayTrack } = useGlobalAudio();

  useEffect(() => {
    const supabase = createClient();
    const getUser = async () => {
      const {
        data: { user },
      } = await supabase.auth.getUser();
      setUser(user);
    };
    getUser();
  }, []); // Remove supabase from dependency array since it's now a singleton

  const handleQuoteClick = useCallback(() => {
    try {
      playOverlayTrack('/audio/dune1-intro.mp3', 'dune1-quote', 'Dune 1 Quote');
    } catch (error) {
      logWarning('Dune 1 audio file not found. Please add dune1-intro.mp3 to /public/audio/', 'Hero');
    }
  }, [playOverlayTrack]);


  return (
    <section className="relative flex h-screen w-full items-center bg-background py-12 md:py-24 lg:py-32 xl:py-48">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col justify-start space-y-8 text-left">
          <div className="space-y-4">
            <div>
              <GlitchWordmark />
              <div className="ss-disambiguation bg-gradient-to-r from-white to-gray-400 bg-clip-text font-mono text-xs tracking-tight text-transparent">
                Software From The Future.
              </div>
            </div>
            <h1 className="ss-disambiguation bg-gradient-to-r from-white to-gray-400 bg-clip-text font-mono text-xs tracking-tight text-transparent sm:text-xs sm:leading-tight xl:text-xs/none xl:leading-tight">
              Product 01 : Neuramance DeepStrategy™
              <br></br>Superintelligent Optimization & Improvement of Processes, Operations, Strategic Plans, System Designs, & Growth Campaigns.
            </h1>
            <div className="flex flex-col items-start">
              <div className="flex flex-col items-center">
                <Icons.faceLevel style={{ width: 150, height: 'auto' }} />
                <div style={{ height: 3 }} />
                {user ? (
                  <Button
                    size="nav"
                    variant="secondary"
                    className="gap-1"
                    disabled
                    aria-label="User is already on the waitlist"
                  >
                    <Check className="h-3 w-3" aria-hidden="true" />
                    Thank you very much for your interest. You are on the
                    waitlist.
                  </Button>
                ) : (
                  <Link
                    href="/signup"
                    className="block"
                  >
                    <Button 
                      size="nav" 
                      variant="secondary" 
                      className="gap-1"
                      aria-label="Sign up for Neuramance waitlist and beta access"
                    >
                      <Plus className="h-3 w-3" aria-hidden="true" />
                      Sign up for Waitlist / Beta
                    </Button>
                  </Link>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* Bottom Centered h1 */}
      <h1
        className="ss-disambiguation absolute bottom-2 left-1/2 -translate-x-1/2 transform px-4 text-center font-mono text-[10px] tracking-tight text-white hover:cursor-pointer sm:text-[10px] sm:leading-tight md:text-[11px] xl:text-[10px]/none xl:leading-tight"
        onClick={handleQuoteClick}
        role="button"
        tabIndex={0}
        onKeyDown={(e) => e.key === 'Enter' && handleQuoteClick()}
        aria-label="Play Dune 1 audio quote"
      >
        Truth is a pathless land, it&apos;s murmur a guiding star from the
        Outside, intuitable only in brief moments of rapture.
      </h1>
    </section>
  );
});

Hero.displayName = 'Hero';
